packages:
  - '.'
  - 'apps/*'

allowBuilds:
  esbuild: true
  workerd: true

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - esbuild
  - react-native
  - react-native-reanimated
  - react-native-worklets
  - workerd
